#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path:       /login
    controller: App\Security\SecurityController::login
    methods: POST
login_check:
    path:     /login_check
    methods:  [POST]